"""Season overlay archetype: data/season-2627.json + data/season-2627.js.

`season-toggle.js` reads `window.FI_SEASON_DATA` from the generated JS and
rewrites the hub cards and report signal blocks client-side, so the JSON shape
and key order here are a runtime contract, not cosmetics.

Seed source is `data/season-2627.js`, not the `.json`: at cutover time the JS
carried a matchweek of data (nicolo-tresoldi's 2026-27 block) that had never
been written back to the JSON, and the JS is what the browser actually loads.
Seeding from the superset keeps live behaviour identical and lets the build
bring the JSON back into sync.
"""

from __future__ import annotations

import json
import sqlite3

from . import read_text, write_page

ORDER = 20

SEASON = "2026-27"
BASE_SEASON = "2025-26"
JSON_PATH = "data/season-2627.json"
JS_PATH = "data/season-2627.js"
JS_ASSIGN = "window.FI_SEASON_DATA = "
JS_HEADER = "/* Auto-generated by build.py — do not edit directly */\n"

COMMENT = (
    "2026-27 current season live data. Updated weekly by scripts/update-stats.py."
    " All values start as pending and are filled in after each matchweek."
)


def parse_js(text: str) -> dict:
    """Extract the JSON payload from the `window.FI_SEASON_DATA = …;` wrapper."""
    payload = text[text.index(JS_ASSIGN) + len(JS_ASSIGN) :]
    return json.loads(payload.rstrip().removesuffix(";"))


def seed(conn: sqlite3.Connection) -> None:
    data = parse_js(read_text(JS_PATH))
    assert data["_comment"] == COMMENT, "season _comment drifted from build constant"
    assert data["season"] == SEASON, data["season"]

    on_disk = json.loads(read_text(JSON_PATH))
    stale = [k for k, v in data["players"].items() if on_disk["players"].get(k) != v]
    if stale:
        print(
            f"  note: {JSON_PATH} lagged {JS_PATH} for {', '.join(stale)}"
            " — seeding from the JS and resyncing the JSON"
        )

    conn.execute(
        "INSERT INTO seasons (season, updated, matchweek) VALUES (?,?,?)",
        (SEASON, data["updated"], data["matchweek"]),
    )

    known = [r["id"] for r in conn.execute("SELECT id FROM players ORDER BY sort")]
    assert list(data["players"]) == known, "season player order differs from hub order"

    for pid, entry in data["players"].items():
        for idx, signal in enumerate(entry["signals"]):
            conn.execute(
                "INSERT INTO season_signals (player_id, season, idx, num, bar, pctl)"
                " VALUES (?,?,?,?,?,?)",
                (pid, SEASON, idx, signal["num"], signal["bar"], signal["pctl"]),
            )
        for idx, metric in enumerate(entry["current_block"]):
            conn.execute(
                "INSERT INTO season_metrics (player_id, season, idx, label, val)"
                " VALUES (?,?,?,?,?)",
                (pid, SEASON, idx, metric["label"], metric["val"]),
            )
        # The overlay carries no stat labels: the three card slots are the same
        # metrics as the base season, so labels are inherited by index.
        labels = [
            r["label"]
            for r in conn.execute(
                "SELECT label FROM card_stats WHERE player_id = ? AND season = ?"
                " ORDER BY idx",
                (pid, BASE_SEASON),
            )
        ]
        assert len(labels) == len(entry["card"]), f"{pid}: card slot count mismatch"
        for idx, card in enumerate(entry["card"]):
            conn.execute(
                "INSERT INTO card_stats (player_id, season, idx, label, val, cls)"
                " VALUES (?,?,?,?,?,?)",
                (pid, SEASON, idx, labels[idx], card["val"], card["cls"]),
            )
        conn.execute(
            "INSERT INTO player_season (player_id, season, mins) VALUES (?,?,?)",
            (pid, SEASON, entry["mins"]),
        )


def entry(conn: sqlite3.Connection, player_id: str) -> dict | None:
    """Rebuild one player's overlay entry — same shape and key order as the JSON.

    None when the player has no overlay rows yet, so a freshly tracked player
    always compares as changed against freshly scraped data.
    """
    row = conn.execute(
        "SELECT mins FROM player_season WHERE player_id = ? AND season = ?",
        (player_id, SEASON),
    ).fetchone()
    if row is None:
        return None
    return {
        "signals": [
            {"num": r["num"], "bar": r["bar"], "pctl": r["pctl"]}
            for r in conn.execute(
                "SELECT num, bar, pctl FROM season_signals WHERE player_id = ?"
                " AND season = ? ORDER BY idx",
                (player_id, SEASON),
            )
        ],
        "current_block": [
            {"label": r["label"], "val": r["val"]}
            for r in conn.execute(
                "SELECT label, val FROM season_metrics WHERE player_id = ?"
                " AND season = ? ORDER BY idx",
                (player_id, SEASON),
            )
        ],
        "card": [
            {"val": r["val"], "cls": r["cls"]}
            for r in conn.execute(
                "SELECT val, cls FROM card_stats WHERE player_id = ? AND season = ?"
                " ORDER BY idx",
                (player_id, SEASON),
            )
        ],
        "mins": row["mins"],
    }


def upsert_entry(conn: sqlite3.Connection, player_id: str, values: dict) -> None:
    """Replace one player's overlay rows with `values` (shape of `entry`).

    Rows are deleted first so a shorter metric block shrinks cleanly instead of
    leaving stale high-index rows behind.
    """
    for table in ("season_signals", "season_metrics", "card_stats"):
        conn.execute(
            f"DELETE FROM {table} WHERE player_id = ? AND season = ?",
            (player_id, SEASON),
        )
    conn.execute(
        "DELETE FROM player_season WHERE player_id = ? AND season = ?",
        (player_id, SEASON),
    )

    for idx, signal in enumerate(values["signals"]):
        conn.execute(
            "INSERT INTO season_signals (player_id, season, idx, num, bar, pctl)"
            " VALUES (?,?,?,?,?,?)",
            (player_id, SEASON, idx, signal["num"], signal["bar"], signal["pctl"]),
        )
    for idx, metric in enumerate(values["current_block"]):
        conn.execute(
            "INSERT INTO season_metrics (player_id, season, idx, label, val)"
            " VALUES (?,?,?,?,?)",
            (player_id, SEASON, idx, metric["label"], metric["val"]),
        )
    labels = [
        r["label"]
        for r in conn.execute(
            "SELECT label FROM card_stats WHERE player_id = ? AND season = ?"
            " ORDER BY idx",
            (player_id, BASE_SEASON),
        )
    ]
    for idx, card in enumerate(values["card"]):
        conn.execute(
            "INSERT INTO card_stats (player_id, season, idx, label, val, cls)"
            " VALUES (?,?,?,?,?,?)",
            (player_id, SEASON, idx, labels[idx], card["val"], card["cls"]),
        )
    conn.execute(
        "INSERT INTO player_season (player_id, season, mins) VALUES (?,?,?)",
        (player_id, SEASON, values["mins"]),
    )


def bump(conn: sqlite3.Connection, updated: str) -> int:
    """Stamp the season as refreshed and advance the matchweek; returns the new one."""
    conn.execute(
        "UPDATE seasons SET updated = ?, matchweek = matchweek + 1 WHERE season = ?",
        (updated, SEASON),
    )
    return conn.execute(
        "SELECT matchweek FROM seasons WHERE season = ?", (SEASON,)
    ).fetchone()["matchweek"]


def payload(conn: sqlite3.Connection) -> dict:
    season = conn.execute(
        "SELECT updated, matchweek FROM seasons WHERE season = ?", (SEASON,)
    ).fetchone()
    players = {}
    for row in conn.execute(
        "SELECT p.id FROM players p JOIN player_season s ON s.player_id = p.id"
        " AND s.season = ? ORDER BY p.sort",
        (SEASON,),
    ):
        players[row["id"]] = entry(conn, row["id"])
    return {
        "_comment": COMMENT,
        "season": SEASON,
        "updated": season["updated"],
        "matchweek": season["matchweek"],
        "players": players,
    }


def build(conn: sqlite3.Connection, env) -> None:
    # The JSON has no trailing newline today; the JS terminates the assignment.
    text = json.dumps(payload(conn), ensure_ascii=False, indent=2)
    write_page(JSON_PATH, text)
    write_page(JS_PATH, f"{JS_HEADER}{JS_ASSIGN}{text};\n")
